import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ConfettiProvider } from "@/providers/Confetti-provider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    
    <html lang="en">
    <ConfettiProvider/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white w-full flex flex-row overflow-x-hidden` }
      >
     
        
          {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
